<h1 class="center-align">Web Developer - Website creation - WebMaster </h1>
		<p class="center-align">
  			Checkout all the languages and framework i've been studying during the past and that i totaly master now ! There are more incoming !
  		</p>
		<div class="carousel">
		    <a class="carousel-item" href="#one!"><img alt="css logo" src="img/css.png"></a>
		    <a class="carousel-item" href="#two!"><img alt="html logo" src="img/html.png"></a>
		    <a class="carousel-item" href="#three!"><img alt="jquery logo" src="img/jquery.png"></a>
		    <a class="carousel-item" href="#four!"><img alt="javascript logo" src="img/js.png"></a>
		    <a class="carousel-item" href="#five!"><img alt="php logo" src="img/php.png"></a>
		    <a class="carousel-item" href="#six!"><img alt="mysql logo" src="img/sql.png"></a>
		    <a class="carousel-item" href="#seven!"><img alt="wordpress logo" src="img/wordpress.png"></a>
		    <a class="carousel-item" href="#eight!"><img alt="symfony logo" src="img/symfony.png"></a>

  		</div>
  		<div class="row">
	  		<section  class="col s12 m12 l6">
	    		<h3 class="header truncate"> Web development </h3>
	   				<div class="card horizontal">
	     				<div class="card-image">
	        				<img class="size" alt="webdeveloper" src="img/webdevpicto.png">
	      				</div>
	     					<div class="card-stacked">
	       						<div class="card-content">
	          						<ul>
	  									<li>App : JavaScript / JQuery</li>
  										<li>Dynamic website : POO PhP  </li>
						  				<li>Data Base : MySql</li>
						  				<li>Frameworks : Symfony</li>
						  			</ul>
	       						</div>
	        					<div class="card-action">
	          						<a href="contact">Contact me </a>
	        					</div>
	      					</div>
	    			</div>
	  			</section>
	  			<section class="col s12 m12 l6">
	    		<h3 class="header truncate">Website creation </h3>
	   				<div class="card horizontal">
	     				<div class="card-image">
	        				<img  alt="webcreation" src="img/webcreapicto.png">
	      				</div>
	     					<div class="card-stacked">
	       						<div class="card-content">
	          						<ul>
	  									<li>HTML - CSS</li>
	  									<li>WordPress</li>
						  				<li>Responsive Template</li>
						  				<li>Rework, migration, security</li>
						  			</ul>
	       						</div>
	        					<div class="card-action">
	          						<a href="contact">Contact me </a>
	        					</div>
	      					</div>
	      			</div>
	    		</section>
	  	</div>
	  		