<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  	<title>D.E V</title>
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet"> 
  	<script src="js/jquery.min.js"></script>
	<script src="https://use.fontawesome.com/e2eec91983.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>




  	<link rel="stylesheet" type="text/css" href="css/style.css">
	
</head>
<body>
	<header>
		 <div>
			<div class="grey lighten-3">
				<a href="portfolio-web.php" class="waves-effect waves-light btn-large red darken-3"><i class="fa fa-book" aria-hidden="true"></i>
				Portfolio</a>
				<span id="url" class="right hide-on-small-only">duschewen.com</span>
			</div>
		</div>
		<div>
			<h1 class="center-align"><span class="grey-text">D.E</span> V</h1>
		</div>
		
			 <nav>
    			<div class="nav-wrapper light-blue darken-3 sticky">
    				<a href="#" class="brand-logo" id="logo"><span class="grey-text">D.E</span> V</a>
      				<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i>Menu</a>
      				<ul class="right hide-on-med-and-down container">
        				<li>
	        				<a href="index.php">
	        				<i class="fa fa-home" aria-hidden="true"></i>
								Home
							</a>
						</li>
						<li>
							<a href="contact.php">
							<i class="fa fa-phone" aria-hidden="true"></i>
							Contact
							</a>
						</li>
						<li id="portfolio">
							<a href="portfolio-web.php" class="waves-effect waves-light btn-large red darken-3">Portfolio</a>
						</li>
     				</ul>
     				<ul class="side-nav" id="mobile-demo">
     					<li>
	     					<a href="portfolio-web.php" class="waves-effect waves-light btn red darken-3">
							Portfolio
							</a>
						</li>
				        <li><a href="index.php">Home</a></li>
						<li><a href="contact.php">Contact</a></li>
      				</ul>
    			</div>
 			 </nav>
		
	</header>
	<main class="container">
	  	<?php include "$template.phtml"; ?>
	</main>

    <footer class="page-footer light-blue darken-3">
        <div class="container">
            <div class="row">
            	<div class="col l6 s12">
                	<h5 class="white-text">I'm up for every propositions</h5>
                	<p class="grey-text text-lighten-4"><strong> DUSCH EWEN DEVELOPMENT - WEBSITE CREATION - INTEGRATOR</strong></p>
                	<p class="grey-text text-lighten-4">Check my Portfolio to see  all my creations.</p>
                	<a href="portfolio-web.php" class="waves-effect waves-light btn-large red darken-3"><i class="fa fa-book" aria-hidden="true"></i>
				Portfolio</a>
              	</div>
              	<div class="col l4 offset-l2 s12">
                	<h5 class="white-text">Follow me on :</h5>
	                <ul>
	                  <li><a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/ewen-dusch-76b999133">
	                  <i class="fa fa-linkedin-square" aria-hidden="true"></i>
	                  Linkedin</a></li>
	                  <li><a class="grey-text text-lighten-3" href="https://github.com/ewendu">
	                  <i class="fa fa-github" aria-hidden="true"></i>

	                  GitHub</a></li>
	                  <li><a class="grey-text text-lighten-3" href="#">
	                  <i class="fa fa-twitter" aria-hidden="true"></i>
	                  Twitter</a></li>

	                  
	                </ul>
              	</div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
            © 2016 Copyright Dusch Ewen
            <a class="grey-text text-lighten-4 right" href="contact.php">Contact me !</a>
            </div>
        </div>
        </footer>
            
            
            
<script type="text/javascript">
$(document).ready(function(){
$('.carousel').carousel();});
$(".button-collapse").sideNav();	
jQuery(function($){
$(document).ready(function(){
$(function(){
$(window).scroll(function(){
var scroll = $(window).scrollTop();
if (scroll >= 280){
$(".sticky").addClass('smaller');
} else { $(".sticky").removeClass("smaller");} 
}); }); }); }); 
//$('#textarea1').val('Your message');
$('#textarea1').trigger('autoresize');
</script>
</body>
</html>