<article class="center-align">
<h1 class="center-align">Portfolio Web</h1>
<h3>App development projects :</h3>
<section class="center-align portfolio">
	<img alt="screenMagicSlate" src="img/portfolio/screen_magicslate.PNG">
	<p>A Magic Slate using Canvas / Objects Oriented JavaScript.</p>
	<a class="check"  href="https://ewendu.github.io/Magic-Slate-V2/">Check it out !</a>
</section>
<h3>Website creation :</h3>
<section class="center-align portfolio">
	<img alt="screenDEV" src="img/portfolio/screen_DEV.PNG">
	<p>The whole creation of this website, using Materialize and jQuery plugins.</p>
	
</section>
<!--<section  class="center-align portfolio">
	<img src="img/portfolio/">
	<p>A little Blog unfortunatly not online.</p>
	<a class="check"  href="https://github.com/ewendu/Blog">Check the source code on GitHub !</a>
</section>-->
<h3 class="center-align">More projects coming soon ... </h3>
<section></section>
<section></section>
<section></section>
<section></section>
<section></section>
</article>