<article class="center-align">
	<h1 class="center-align">Portfolio Web</h1>
	<h3>Website creation </h3>
	<section class="center-align portfolio">
		<img alt="screenDEV" src="img/portfolio/screen_DEV.PNG">
		<p>The whole creation of this website, using Materialize and jQuery plugins.</p>
		
	</section>
	<section  class="center-align portfolio">

		<div class="carousel carousel-slider center" data-indicators="true">
    		<div class="carousel-fixed-item center">
      			<a href="https://github.com/ewendu/Blog" class="btn waves-effect white grey-text darken-text-2">Source Code</a>
    		</div>
    		<a class="carousel-item white-text" href="#one!">
      			<img src="img/portfolio/CaptureAddPostBlog.png" alt="" />
    		</a>
		    <a class="carousel-item white-text" href="#two!">
		      <img src="img/portfolio/CaptureAdminBlog.png" alt="" />
		    </a>
		    <a class="carousel-item white-text" href="#three!">
		      <img src="img/portfolio/CaptureCatBlog.png" alt="" />
		    </a>
		    <a class="carousel-item white-text" href="#four!">
		      <img src="img/portfolio/CaptureHomeblog.png" alt="" />
		    </a>
  		</div>
  		<p>A little science blog i've been creating in PhP. Unfortunatly not online but you can see the source code on GitHub.</p>
	</section>
	<h3>App development projects </h3>
	<section class="center-align portfolio">
		<img alt="screenMagicSlate" src="img/portfolio/screen_magicslate.PNG">
		<p>A Magic Slate using Canvas / Objects Oriented JavaScript.</p>
		<a class="check"  href="https://ewendu.github.io/Magic-Slate-V2/">Check it out !</a>
	</section>
	<h3 class="center-align">More projects coming soon ... </h3>
	<!--<section></section>
	<section></section>
	<section></section>
	<section></section>
	<section></section>-->
</article>